
transpiler:
  build: .
  volumes_from:
    - data
  # typescript should watch the src directory
  command: tsc -w --outDir dist/

server:
  build: .
  volumes_from:
    - data
  # nodemon should watch the dist directory
  command: sh -c "touch dist/index.js && nodemon dist/index.js -d 300ms -w dist"
  env_file: .env
  expose:
    - 3001
  ports: 
    - 3001:3001

data:
  build: .
  volumes:
    - .:/app            # share your code with the containers
    - /app/dist         # container has its own dist directory
    - /app/node_modules # container has its own node_modules directory
  command: 'true'