transpiler:
  build: .
  volumes_from:
    - data
  command: npm run transpiler

server:
  build: .
  volumes_from:
    - data
  command: npm run server-dev
  env_file: .env
  expose:
    - 3001
  ports: 
    - 3001:3001

data:
  build: .
  volumes:
    - .:/app
    - /app/dist
    - /app/node_modules
  command: 'true'